a=input("Enter Your Name: ")
print(f"Good Evening... {a},")
print("Please Take your Dinner.")
b=input("How was your day ? ")
print(f"thanks... {a} to tell me about you")
print("Good Night, Sweet Dreams :)")