import time
print('m', end='', flush=True)
time.sleep(1)
print('o', end='', flush=True)
time.sleep(1)
print('h', end='', flush=True)
time.sleep(1)
print('a', end='', flush=True)
time.sleep(1)
print('n', end='', flush=True)
time.sleep(1)
print('\r', end='', flush=True)
time.sleep(1)
print('\r', end='', flush=True)
time.sleep(1)
print('r', end='', flush=True)
time.sleep(1)
print('a', end='', flush=True)
time.sleep(1)
print('m', end='', flush=True)