import time
print('R', end='', flush=True)
time.sleep(1)
print('i', end='', flush=True)
time.sleep(1)
print('t', end='', flush=True)
time.sleep(1)
print('e', end='', flush=True)
time.sleep(1)
print('s', end='', flush=True)
time.sleep(1)
print('h', end='', flush=True)
time.sleep(1)
print('\b', end='', flush=True)
time.sleep(1)
print('\b', end='', flush=True)
time.sleep(1)
print('\b', end='', flush=True)
time.sleep(1)
print('\b', end='', flush=True)
time.sleep(1)
print('\b', end='', flush=True)
time.sleep(1)
print('a', end='', flush=True)
time.sleep(1)
print('c', end='', flush=True)
time.sleep(1)
print('h', end='', flush=True)
time.sleep(1)
print('i', end='', flush=True)
time.sleep(1)
print(' ', end='', flush=True)