import time
X=0.6
print('R', end='', flush=True)
time.sleep(X)
print('i', end='', flush=True)
time.sleep(X)
print('t', end='', flush=True)
time.sleep(X)
print('e', end='', flush=True)
time.sleep(X)
print('s', end='', flush=True)
time.sleep(X)
print('h', end='', flush=True)
time.sleep(X)
print('\b', end='', flush=True)
time.sleep(X)
print('\b', end='', flush=True)
time.sleep(X)
print('\b', end='', flush=True)
time.sleep(X)
print('\b', end='', flush=True)
time.sleep(X)
print('\b', end='', flush=True)
time.sleep(X)
print('a', end='', flush=True)
time.sleep(X)
print('j', end='', flush=True)
time.sleep(X)
print('k', end='', flush=True)
time.sleep(X)
print('u', end='', flush=True)
time.sleep(X)
print('m', end='', flush=True)
time.sleep(X)
print('a', end='', flush=True)
time.sleep(X)
print('r', end='', flush=True)
time.sleep(X)
print('... :)', end='', flush=True)
